server {
    #listen %%interface%%:%%port%% default_server;
    listen %%interface%%:%%port%%;
    #listen 8099;
    #ssl_certilisten ficate /ssl/fullchain.pem;
	#ssl_certificate_key /ssl/privkey.pem;
	
    include /etc/nginx/includes/server_params.conf;
    include /etc/nginx/includes/proxy_params.conf;

    
    location / {
    
        proxy_pass http://127.0.0.1:25600;
        sub_filter_types *;
        #sub_filter "script.src = url" 'script.src ="$http_x_ingress_path/"+url';
        #sub_filter "l.src=i" 'l.src ="$http_x_ingress_path/"+i';
        #sub_filter 'return"css/"' 'return"$http_x_ingress_path/css/"';
        #t.b = "undefined" !== typeof document && document.baseURI || self.location.href;
        #sub_filter 't.b="undefined"!==typeof document&&document.baseURI||self.location.href;' 't.b="";';
        sub_filter "window.resourceBaseUrl = '/'"  "window.resourceBaseUrl = '$http_x_ingress_path/'" ;
        
        #window.resourceBaseUrl = '/'

    }
}

