name: "nginx"
description: "A nginx addon"
version: "0.0.98"
slug: "nginx"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:  
  - type: ssl
    read_only: False
  - type: addon_config
    read_only: false
image: ghcr.io/lolimanko/{arch}-nginx