name: "stash"
description: "Stash is a self-hosted webapp written in Go which organizes and serves your diverse content collection, catering to both your SFW and NSFW needs."
version: "0.0.82"
slug: "stash"
init: false
url: "https://github.com/stashapp/stash"
arch:
  - aarch64
  - amd64
ports:
  9999/tcp: 9999
map:
  - type: media
    read_only: False
  - type: share
    read_only: false
  - type: addon_config
    read_only: false
    path: /root/.stash

image: ghcr.io/lolimanko/{arch}-stash