name: "stash"
description: "Stash is a self-hosted webapp written in Go which organizes and serves your diverse content collection, catering to both your SFW and NSFW needs."
version: "0.31.1"
slug: "stash"
url: https://github.com/stashapp/stash
init: false
#host_network: true
ports:
  9999/tcp: 9999
  10000/tcp: 10000
ports_description:
  9999/tcp: http
  10000/tcp: https
arch:
  - aarch64
  - amd64
map:
  - type: ssl
    read_only: False
  - type: media
    read_only: False
  - type: share
    read_only: false
  - type: addon_config
    read_only: false
    path: /root/.stash
ingress: true 
#ingress_port: 5000
ingress_stream: true
#ingress_stream: false
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
panel_icon: mdi:video-box
image: "ghcr.io/lolimanko/{arch}-stash" 