server {
    #listen %%interface%%:%%port%% default_server;
    listen %%interface%%:%%port%%;
    
    #ssl_certificate /ssl/fullchain.pem;
	#ssl_certificate_key /ssl/privkey.pem;
	
    include /etc/nginx/includes/server_params.conf;
    include /etc/nginx/includes/proxy_params.conf;

    
    location / {
    
        proxy_pass http://127.0.0.1:9999;
        
    }

}

